**: {
  style: {
    font-size: 30
  }
}

(** -> **)[*]: {
  style: {
    stroke: "#000000"
    font-size: 30
  }
}

(** <- **)[*]: {
  style: {
    stroke: "#000000"
    font-size: 30
  }
}

(** <-> **)[*]: {
  style: {
    stroke: "#000000"
    font-size: 30
  }
}
direction: right
azure: "" {
  style: {
    stroke: "#000000"
    stroke-dash: 3
    fill: transparent
  }

  grid-rows: 1

  stream1: Stream 1 (Azure Management Group) {
    style: {
      stroke: transparent
      fill: "#ecf3fb"
    }

    cbr1: CBR 1 (shared) {
      subscription: "" {
        style: {
          stroke: "#d2b34e"
          fill: "#fff2cc"
        }

        vnet: Default VNet 10.0.0.0/8 {
          style: {
            stroke: "#000000"
            font-color: "#000000"
            stroke-dash: 3
            fill: transparent
          }

          fw: Firewall: 80/443 {
            style: {
              stroke: black
              font-color: black
              stroke-dash: 3
              fill: transparent
            }

            app1: Experiment 1
          }
        }

        subscriptionicon: "" {
          grid-rows: 1
          grid-gap: 0
          style: {
            stroke: transparent
            fill: transparent
          }
          subicon: "" {
            icon: https://raw.githubusercontent.com/sleepycat/diagrams/refs/heads/main/icons/azure/Icons/general/10002-icon-service-Subscriptions.svg
            width: 50
            height: 50
            shape: image
          }
          Application subscription.style: {
            stroke: transparent
            fill: transparent
          }
        }
      }
    }
  }

  stream2: Stream 2 (Azure Management Group) {
    grid-rows: 3
    grid-gap: 100
    style: {
      stroke: transparent
      fill: "#ecf3fb"
    }

    cbr2: CBR 2 (shared) {
      alpha: Alpha workloads {
        grid-rows: 1
        subscription: "" {
          direction: down
          style: {
            stroke: "#d2b34e"
            fill: "#fff2cc"
          }

          vnet: Default VNet 10.1.0.0/16 {
            style: {
              stroke: "#000000"
              font-color: "#000000"
              stroke-dash: 3
              fill: transparent
            }

            fw: Firewall: 80/443 {
              style: {
                stroke: black
                font-color: black
                stroke-dash: 3
                fill: transparent
              }

              app2: Alpha 1
            }
          }
          subscriptionicon: "" {
            grid-rows: 1
            grid-gap: 0
            style: {
              stroke: transparent
              fill: transparent
            }
            subicon: "" {
              icon: https://raw.githubusercontent.com/sleepycat/diagrams/refs/heads/main/icons/azure/Icons/general/10002-icon-service-Subscriptions.svg
              width: 50
              height: 50
              shape: image
            }
            Application subscription.style: {
              stroke: transparent
              fill: transparent
            }
          }
        }

        subscription2: "" {
          style: {
            stroke: "#d2b34e"
            fill: "#fff2cc"
          }

          vnet: Default VNet 10.1.0.0/16 {
            style: {
              stroke: "#000000"
              font-color: "#000000"
              stroke-dash: 3
              fill: transparent
            }

            fw: Firewall: 80/443 {
              style: {
                stroke: black
                font-color: black
                stroke-dash: 3
                fill: transparent
              }

              app2: Alpha 2
            }
          }

          subscriptionicon: "" {
            grid-rows: 1
            grid-gap: 0
            style: {
              stroke: transparent
              fill: transparent
            }
            subicon: "" {
              icon: https://raw.githubusercontent.com/sleepycat/diagrams/refs/heads/main/icons/azure/Icons/general/10002-icon-service-Subscriptions.svg
              width: 50
              height: 50
              shape: image
            }
            Application subscription.style: {
              stroke: transparent
              fill: transparent
            }
          }
        }
      }

      beta: Beta Workloads {
        subscription2: "" {
          direction: down
          style: {
            stroke: "#d2b34e"
            fill: "#fff2cc"
          }

          vnet: Default VNet 10.1.0.0/16 {
            style: {
              stroke: "#000000"
              font-color: "#000000"
              stroke-dash: 3
              fill: transparent
            }

            fw: Firewall: 80/443 {
              style: {
                stroke: black
                font-color: black
                stroke-dash: 3
                fill: transparent
              }

              app2: Beta 1
            }
          }

          subscriptionicon: "" {
            grid-rows: 1
            grid-gap: 0
            style: {
              stroke: transparent
              fill: transparent
            }
            subicon: "" {
              icon: https://raw.githubusercontent.com/sleepycat/diagrams/refs/heads/main/icons/azure/Icons/general/10002-icon-service-Subscriptions.svg
              width: 50
              height: 50
              shape: image
            }
            Application subscription.style: {
              stroke: transparent
              fill: transparent
            }
          }
        }
      }
    }

    live: Live Workloads (CBR per workload) {
      cbr3: CBR 3 (dedicated) {
        subscription: "" {
          direction: down
          style: {
            stroke: "#d2b34e"
            fill: "#fff2cc"
          }

          vnet: Default VNet 10.1.0.0/16 {
            style: {
              stroke: "#000000"
              font-color: "#000000"
              stroke-dash: 3
              fill: transparent
            }

            fw: Firewall: 80/443 {
              style: {
                stroke: black
                font-color: black
                stroke-dash: 3
                fill: transparent
              }

              app2: Live 1
            }
          }

          subscriptionicon: "" {
            grid-rows: 1
            grid-gap: 0
            style: {
              stroke: transparent
              fill: transparent
            }
            subicon: "" {
              icon: https://raw.githubusercontent.com/sleepycat/diagrams/refs/heads/main/icons/azure/Icons/general/10002-icon-service-Subscriptions.svg
              width: 50
              height: 50
              shape: image
            }
            Application subscription.style: {
              stroke: transparent
              fill: transparent
            }
          }
        }
      }

      cbr4: CBR 4 (dedicated) {
        subscription: "" {
          direction: down
          style: {
            stroke: "#d2b34e"
            fill: "#fff2cc"
          }

          vnet: Default VNet 10.1.0.0/16 {
            style: {
              stroke: "#000000"
              font-color: "#000000"
              stroke-dash: 3
              fill: transparent
            }

            fw: Firewall: 80/443 {
              style: {
                stroke: black
                font-color: black
                stroke-dash: 3
                fill: transparent
              }

              app2: Live 2
            }
          }

          subscriptionicon: "" {
            grid-rows: 1
            grid-gap: 0
            style: {
              stroke: transparent
              fill: transparent
            }
            subicon: "" {
              icon: https://raw.githubusercontent.com/sleepycat/diagrams/refs/heads/main/icons/azure/Icons/general/10002-icon-service-Subscriptions.svg
              width: 50
              height: 50
              shape: image
            }
            Application subscription.style: {
              stroke: transparent
              fill: transparent
            }
          }
        }
      }
    }
  }

  azureicon: "" {
    icon: https://raw.githubusercontent.com/sleepycat/diagrams/refs/heads/main/icons/azure/text-logo.svg
    width: 300
    shape: image
  }
}

azure.stream2.cbr2.alpha -> azure.stream2.cbr2.beta: graduation\ncriteria met
azure.stream2.cbr2.beta -> azure.stream2.live.cbr4: graduation\ncriteria met

explanation: |md
  In the Government of Canada, SSC's [cloud framework agreement](https://hosting-services-hebergement.canada.ca/s/gc-cloud-fa-catalogue?language=en_US) dictates cloud spending requires a [Cloud Business Requirement](https://hosting-services-hebergement.canada.ca/s/article/What-is-a-Cloud-Business-Requirement?language=en_US) (CBR) number. 

  The bureaucratic overhead/turnaround time and spending limits associated with a CBR require care to ensure service delivery isn't negatively affected.

  The following approach is designed to support experimentation and rapid onboarding of teams in support of the "product team" model.

  ## Stream 1: Time-bound experiments
  * These represent hands-on experiments and evaluations aimed at building knowledge/skills.
  * Isolated spaces (dedicated subscriptions) allows for enablement and live data <br/>(live data is required for AI/ML experimentation).
  * CBR strategy:
    * Drawing down on a shared CBR reduces bureaucratic overhead to experimentation and enables rapid intake.

  ## Stream 2: Capability development: Alpha, Beta, Live
  * Three "production" environments based on team/product maturity levels:
    * **Alpha**: Polished subset of eventual functionality, low operational maturity (eg: uptime, respect for data contracts); Try, don't rely.
    * **Beta**: Expanded functionality, higher operational maturity (eg: have stated uptime objectives, might not meet them); Use, but excuse.
    * **Live**: Functionality tracks evolving user needs, high operational maturity; this is a service others can rely on.
  * Define graduation criteria upfront, move when maturity markers are achieved.
  * CBR strategy:
    * Rapid intake of Alpha/Beta workloads into shared CBR.
    * Workloads/costs distributed across Alpha/Beta CBRs.
    * Graduation to Beta kicks off background process to create a dedicated CBR for Live.
    * Capability teams shielded from CBR process.
  * Security boundaries create autonomy needed for capability delivery:
    * Limit blast radius with dedicated projects/accounts: insulates organization/others from team failure/compromise.
    * With limited blast radius, we can safely increase privilege inside projects/accounts: creates enabling environment supporting team autonomy.
  * Contrast:
    * "dev/test/prod": building trust in code.
    * "alpha/beta/live": building trust in teams.
  <br/>
  <br/>

| {near: center-right}
