direction: down
TDD <- Continuous Deployment: depends on
Build Automation <- Continuous Deployment: depends on
Framework choice <- Continuous Deployment: depends on
Infrastructure <- Continuous Deployment: depends on
Dev Practices <- Continuous Deployment: depends on
Observability <- Continuous Deployment: depends on
