explanation: |md
  # Current interaction model
  Data science interacts with and interprets the needs of epis, and procures systems and infrastructure they feel are needed.<br/> These systems and infrastructure elements are delivered to the infrastructure team to run.
  
This model treats cloud as undifferentiated compute/storage.
| {near: top-center}

grid-rows: 3
EPIs
Data Science
Data Platforms and Infrastructure.width: 500

Data Science -> EPIs
Data Platforms and Infrastructure <- Data Science
