explanation: |md
  # Improved interaction model
  Google Cloud offers many services intended for direct consumption by people doing analytical work.

  Data scientists and epidemiologists are both examples.

  In this model, DPI interacts with both groups to get them accessing cloud using high level cloud services.

This avoids unnessary cost and maintainance/operational burden for duplicative services.
| {
  near: top-center
}

grid-rows: 2
Data Science
EPIs
Data Platforms and Infrastructure.width: 500

Data Science -> EPIs
Data Platforms and Infrastructure -> Data Science
Data Platforms and Infrastructure -> EPIs
