vars: {
  d2-config: {
    layout-engine: elk
    # Terminal theme code
    theme-id: 1
  }
}

**.style.font-size: 30

catalog: IPPD Service Catalog {
  grid-columns: 3
  style: {
    fill: transparent
    font-size: 50
  }
  facilitation: Facilitation {
    grid-columns: 1
    style: {
      font-size: 50
    }
    Using Version Control
    Geospatial Analysis
    Cloud/data architecture review
    Python/R for data analysis
    Python/R for data ingestion/cleaning
    Synthetic data generation
  }

  collab: Collaboration {
    grid-columns: 1
    style: {
      font-size: 50
    }
    Application Development
    Application deployment
    API creation
    Observability
  }

  service: X-as-a-service {
    grid-columns: 1
    style: {
      font-size: 50
    }
    dns: Self serve graduated DNS: alpha, beta live
    Experimental cloud space
    Pre-production cloud space
    Data analysis environments
    Dev environments
    AI/ML platform and tools
    Geocoding
    Routing
    SDMX
  }
}

explanation: |md
  # IPPD service catalog
  The IPPD team groups its service offerings according to the interaction modes defined by the Team Topologies model:

  * Collaboration: working together for a defined period of time to discover new things (APIs, practices, technologies, etc.)
  * X-as-a-Service: one team provides and one team consumes something “as a Service”k
  * Facilitation: one team helps and mentors another team

  Following this model allows for clear interactions between IPPD and other teams.
|
